version: "3.8"
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: synobridge
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=America/New_York   # Change to your timezone
    volumes:
      - /volume1/configs/radarr:/config
      - /volume1/data/movies:/movies
      - /volume1/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped 