version: "3.8"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: synobridge
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=America/New_York   # Change to your timezone
      - WEBUI_PORT=8080
    volumes:
      - /volume1/configs/qbittorrent:/config
      - /volume1/downloads:/downloads
    ports:
      - 8080:8080     # Web UI
      - 6881:6881     # BitTorrent port
      - 6881:6881/udp # BitTorrent UDP
    restart: unless-stopped 