radarr:
  radarr:
    base_url: http://192.168.50.92:7878
    api_key: f699493d3d0b4875b0b3601773080
    include:
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web

sonarr:
  sonarr:
    base_url: http://192.168.50.92:8989
    api_key: 420a5075942b40c7908e4bf5910d7a55
    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p 